Feature/fix/p1 406 fix sign up admin
RAMtastic6/EasyMeal pull request #29
Opened 2024-05-22 15:49 UTC by samuele-visentin

Ho sistemato la registrazione admin, ho aggiunto un redirect a login nella registrazione normale cosi l'utente si puo loggare dopo essersi registrato e ho sistemato i relativi test.
La creazione dell'utente admin avviene lato backend con una trasaction.

2024-05-22 15:53 UTC, rzaupa requested changes
La percentuale del coverage del backend è diminuita. Inaccettabile.

2024-05-22 16:30 UTC, samuele-visentin commented
> La percentuale del coverage del backend è diminuita. Inaccettabile.

Chiedo umilemente venia, spero di non commettere più codesto errore

2024-05-22 16:32 UTC, samuele-visentin commented
Ora la percentuale è aumentata!

2024-05-23 10:32 UTC, rzaupa approved these changes
Buona la gestione con le transaction. Le dipendenze nel backend sono aumentate, però solo tra i service e in un modo che sembra ragionevole. Dobbiamo però stare attenti, il diagramma del backend è da rivedere e non sono sicuro che sia comunque il modo migliore per farlo. Data l'urgenza lo approvo sperando di non patire il debito tecnico

2024-05-23 12:47 UTC, merged