Costruita la home page
RAMtastic6/EasyMeal pull request #34
Opened 2024-05-23 14:31 UTC by st3rling02

aggiunto l'immagine easy_meal.png
aggiunto il component "homepage_cards.tsx"
aggiornata la home page

2024-05-23 14:40 UTC, bassupreme requested changes
Ok praticamente va quasi tutto bene.
L'unica cosa è: tu hai messo tutte le classi tail-wind in modo che il sito sia poi responsive.

Provandolo su browser vedo che il ridimensionamento è gestito bene, ma quando si raggiungono le dimensioni mobile, sarebbe meglio avere le due card di registrazione l'una sopra l'altra; se riuscissi a fidarlo sarebbe meglio.

In più sarebbe meglio che tu scrivessi anche gli unit test della pagina home in quanto si vuole arrivare almeno all'80% della coverage in tutti e tre i progetti;

2024-05-23 16:39 UTC, bassupreme approved these changes
Perfetto...ora anche da me su firefox va.

2024-05-23 17:19 UTC, rzaupa requested changes
Non va bene, non c'è il test per il componente homepage_cards.tsx. Effettua il merge con il develop recente per vedere la cartella next-js/_tests_ e per inserire il corrispondente test qui dentro.

2024-05-24 15:07 UTC, bassupreme approved these changes
Bella ora i test vanno e la pagina mi sembra apposto.

2024-05-24 15:09 UTC, bassupreme approved these changes
si può fare il merge

2024-05-25 08:21 UTC, rzaupa approved these changes
Mi sembra tutto a posto

2024-05-25 08:22 UTC, merged