Feature/p1 298 visualizzazione ingredienti piatti
RAMtastic6/EasyMeal pull request #8
Opened 2024-05-12 13:12 UTC by samuele-visentin

Pagina per modificare gli ingredienti, se si ricarica la pagina prima di confermare si perdono le modifiche, una cosa del genere può andare?

2024-05-12 20:46 UTC, rzaupa commented
Il websocket funziona come atteso come anche la visualizzazione degli ingredienti e la loro funzionalità di aggiunta e rimozione ( per verificare che si sia salvato nel db non ho visto ). Bene anche il messaggio di errore nel momento in cui non ho ordinato niente e faccio checkout.

Alcune perplessità:
- se aggiungo un ordine e poi lo rimuovo questo risulterà comunque nella pagina di checkout (quindi basta che faccio un +1 e poi un -1 e questo piatto finirà comunque nella pagina di checkout)... questo perchè quando salvi nel db il quantity può essere anche 0 ma il riferimento a food rimane (nella funzione createOrUpdate)
- te salvi nel db una volta che fai decreaseQuantity o increaseQuantity, ma penso dovresti farlo nel momento in cui fai conferma alla fine (quindi dopo la pagina checkout) e tenere tutto lato client ? da discutere
- le card per la pagina checkout dovrebbero corrispondere ad un ordine e non al piatto in sè (se ho ordinato due piatti di pasta al pomodoro nella pagina checkout dovrei avere due card e non solo una). credo perchè nella funzione getReservationOrders di orders.service non ritorni anche la quantità oltre che le info che hai messo
- cosa strana: se ci sono due client che sono nella pagina checkout e uno aggiorna la pagina perde le modifiche sugli ingredienti, mentre l'altro no, e come funziona quando uno dei due fa conferma? ti salva la prima situazione o la seconda ? questa cosa non succede nella pagina degli ordini... forse conviene fare così ?

In generale:
- tabella days open sparita, wtf
- la gestione del modulo Food ok per separare le responsabilità

Data la complessità della pagina ci sta avere questo tipo di errori o di dubbi

2024-05-15 15:05 UTC, rzaupa commented
1. Secondo me va bene che sia uno a poter confermare per tutti
2. Si può ancora visualizzare il checkout in che senso? Dopo aver fatto conferma? Io farei nella pagina di checkout tipo al posto di "conferma" , "visualizza riepilogo" e poi "conferma" che poi il riepilogo è un requisito. La feature di questo branch però sono gli ingredienti quindi si può fare a parte. Stesso discorso per il punto 1.

2024-05-15 21:26 UTC, samuele-visentin commented
Ho eseguito il merge di develop, in teoria non ho rotto nulla ma se puoi dare un occhiata anche tu meglio @rzaupa

2024-05-16 11:23 UTC, rzaupa requested changes
Allora 
- se faccio checkout subito senza ordinare niente, torno indietro e ordino qualcosa allora nella pagina di checkout non vedo ordini, non saprei bene la causa (se vuoi approfondisco dopo)
- se non ci sono ingredienti da togliere o aggiungere per il piatto non fare visualizzare il nome "Ingredienti" mentre nella pagina di checkout penso possa andare bene (dettaglio comunque)
- bene il controllo "ordine già confermato", in futuro lo cambieremo da alert a qualcos'altro
- problema forse solo mio: con docker non mi funziona il socket, se a te va allora boh sistemerò

Le pagine non mi sembrano rotte

2024-05-16 11:25 UTC, rzaupa approved these changes
Allora 
- se faccio checkout subito senza ordinare niente, torno indietro e ordino qualcosa allora nella pagina di checkout non vedo ordini, non saprei bene la causa (se vuoi approfondisco dopo)  
- se non ci sono ingredienti da togliere o aggiungere per il piatto non fare visualizzare il nome "Ingredienti" mentre nella pagina di checkout penso possa andare bene (dettaglio comunque)
- bene il controllo "ordine già confermato", in futuro lo cambieremo da alert a qualcos'altro
- problema forse solo mio: con docker non mi funziona il socket, se a te va allora boh sistemerò

Le pagine non mi sembrano rotte. Queste modifiche sono già tante comunque, io approverei la pull request e poi sistemerei il resto

2024-05-16 12:29 UTC, merged